# Generated by Django 3.1.5 on 2021-01-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('100', '100 L'), ('200', '200 L'), ('300', '300 L'), ('400', '400 L'), ('500', '500 L'), ('600', '600 L')], max_length=3)),
                ('number', models.CharField(max_length=11)),
                ('total_gb', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
